/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CadastrarScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Cadastros/CadastrarEmpresaScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Cadastros/CadastrarEnderecoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Cadastros/CadastrarEntregadorScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Cadastros/CadastrarUsuarioScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Home/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Home/components/FarmaCard`; params?: Router.UnknownInputParams; } | { pathname: `/Home/components/FarmaPromoCard`; params?: Router.UnknownInputParams; } | { pathname: `/Home/components/FarmaTagButton`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CadastrarScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/LoadingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Cadastros/CadastrarEmpresaScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Cadastros/CadastrarEnderecoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Cadastros/CadastrarEntregadorScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Cadastros/CadastrarUsuarioScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/components/FarmaCard`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/components/FarmaPromoCard`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/components/FarmaTagButton`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/CadastrarScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/LoadingScreen${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Cadastros/CadastrarEmpresaScreen${`?${string}` | `#${string}` | ''}` | `/Cadastros/CadastrarEnderecoScreen${`?${string}` | `#${string}` | ''}` | `/Cadastros/CadastrarEntregadorScreen${`?${string}` | `#${string}` | ''}` | `/Cadastros/CadastrarUsuarioScreen${`?${string}` | `#${string}` | ''}` | `/Home/HomeScreen${`?${string}` | `#${string}` | ''}` | `/Home/components/FarmaCard${`?${string}` | `#${string}` | ''}` | `/Home/components/FarmaPromoCard${`?${string}` | `#${string}` | ''}` | `/Home/components/FarmaTagButton${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CadastrarScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Cadastros/CadastrarEmpresaScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Cadastros/CadastrarEnderecoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Cadastros/CadastrarEntregadorScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Cadastros/CadastrarUsuarioScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Home/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Home/components/FarmaCard`; params?: Router.UnknownInputParams; } | { pathname: `/Home/components/FarmaPromoCard`; params?: Router.UnknownInputParams; } | { pathname: `/Home/components/FarmaTagButton`; params?: Router.UnknownInputParams; };
    }
  }
}
